### PR TITLE
Speeds up db reads

### LINKED ISSUE #8: long messages are very slow
read.table makes popping long messages very slow.

```
  q <- txtq(tempfile())
  s <- paste(sample(LETTERS, 3000000, TRUE), collapse = "")
  q$push(title = "long", message = s)
  out <- q$pop(-1)
  expect_equal(s, out$message)
  q$destroy()
```

### PR DESCRIPTION
**Pull request by ifellows**
Fixes #8

### CODE REVIEW

**Comment by wlandau** [comment]
I just compared speeds with the example in #8, and I love this! Thank you so much!

**Review by wlandau — CHANGES_REQUESTED** [review]
A few minor requests:

- [ ] Would you bump the version to 0.1.2 and describe the change in `NEWS.md`?
- [ ] Could we use `TRUE` and `FALSE` instead of `T` and `F`? Example: 
- [ ] Would you fix [these lints](https://github.com/wlandau/txtq/pull/9#issuecomment-449528463)?
- [ ] If you would like, please feel free to add yourself as a contributor in the `DESCRIPTION` file.

**Comment by ifellows** [comment]
Requested edits made. Can't believe I left a "T" in there. I thought R CMD check would have caught that.

**Comment by wlandau** [comment]
`goodpractice::gp()` catches it with `lintr`.

**Review by wlandau — APPROVED** [review]

**Comment by wlandau** [comment]
Thanks! I think this is a significant improvement to `txtq`.

**Pull request merged**
